---
title: "Microbiome Data Setup"
author: "Brian S. Yandell"
date: "5/12/2017"
params:
  chr_id: '17'
  peak_Mbp: 46
  pheno_name: fat_pad_weight
  window_Mbp: 2
  datapath: "~/Documents/Research/attie_alan/DO/data/DerivedData"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
suppressPackageStartupMessages({
  library(qtl2geno)
  library(qtl2scan)
  library(qtl2ggplot)
  library(qtl2pattern)
  library(qtl2feather)
  library(dplyr)
  library(ggplot2)
  library(stringr)
  library(readr)
})
```

```{r}
pheno_name <- unlist(stringr::str_split(params$pheno_name, ",")[[1]])
chr_id  <- as.character(params$chr_id)
peak_Mbp <- as.numeric(params$peak_Mbp)
window_Mbp <- as.numeric(params$window_Mbp)
datapath <- as.character(params$datapath)
```

```{r}
covar <- readRDS(file.path(datapath, "covar.rds"))
```

```{r}
peaks <- readRDS(file.path(datapath, "peaks.rds"))
peak_info <- (
  dplyr::ungroup(
    dplyr::summarize(
      dplyr::arrange(
        dplyr::distinct(
          dplyr::group_by(peaks, pheno), 
          output), 
        dplyr::desc(output)), 
      output = output[1])
    )
  )$output
peaks <- dplyr::filter(peaks, output %in% peak_info)
```

```{r}
analyses_tbl <- dplyr::filter(readRDS(file.path(datapath, "analyses.rds")), 
                              output %in% peak_info)
```

Look at transformations and covariates used before for OTUs.

```{r}
analyses_tbl %>% 
  filter(pheno_group == "otu") %>% 
  select(transf, offset, winsorize) %>%
  filter(row_number(transf) == 1)
```

```{r}
analyses_tbl %>% 
  filter(pheno_group == "otu") %>% 
  select(9:20) %>%
  filter(row_number(sex) == 1)
```

## Peaks with 0 as NA

```{r}
peaks_na <- read_tsv(file.path(datapath, "otu", 
                               "20170503_peaks_cr97_wNA_ra_wTaxonomy.tsv")) %>%
  mutate(chr = factor(chr, c(1:19,"X"))) %>%
  select(-lodindex) %>%
  rename(pheno = lodcolumn) %>%
  mutate(pheno = paste0("n", pheno),
         longname = paste0(pheno, " (", Order, ")"),
         output = pheno,
         pheno_group = "OTU_Closed_Ref",
         pheno_type = "OTU_NA")
```

```{r}
peaks_na %>%
  count(pheno) %>%
  count(n)
```

```{r}
peaks_na %>%
  select(Phylum:Species) %>%
  group_by(Phylum) %>%
  summarize_all(n_distinct)
```
```{r}
peaks_na %>%
  count(Order)
```

```{r}
peaks_na %>%
  select(Phylum:Species) %>%
  group_by(Phylum) %>%
  summarize_all(funs(sum(is.na(.))))
```

```{r}
table(peaks_na$chr)
```

## Peaks with 0 as 0

```{r}
peaks_zero <- read_tsv(file.path(datapath, "otu", 
                               "20170501_peaks_cr97_w0_ra_wTaxonomy.tsv")) %>%
  mutate(chr = factor(chr, c(1:19,"X"))) %>%
  select(-lodindex) %>%
  rename(pheno = lodcolumn) %>%
  mutate(pheno = paste0("z", pheno),
         longname = paste0(pheno, " (", Order, ")"),
         output = pheno,
         pheno_group = "OTU_Closed_Ref",
         pheno_type = "OTU_Zero")
```

```{r}
peaks_zero %>%
  count(pheno) %>%
  count(n)
```

```{r}
peaks_zero %>%
  select(Phylum:Species) %>%
  group_by(Phylum) %>%
  summarize_all(n_distinct)
```
```{r}
peaks_zero %>%
  count(Order)
```

```{r}
peaks_zero %>%
  select(Phylum:Species) %>%
  group_by(Phylum) %>%
  summarize_all(funs(sum(is.na(.))))
```

```{r}
table(peaks_zero$chr)
```


## Annotation

```{r}
annot <- read_tsv(file.path(datapath, "otu",
                            "phe_otu_cr97_filter1010_taxonomy.tsv")) %>%
  rename(pheno = id) %>%
  mutate(longname = paste0(pheno, " (", Order, ")"),
         output = pheno,
         pheno_group = "OTU_Closed_Ref")
  
```

```{r}
annot <- bind_rows(
  annot %>%
    mutate(pheno = paste0("z", pheno),
           longname = paste0("z", longname),
           output = paste0("z", output),
           pheno_type = "OTU_Zero"),
  annot %>%
    mutate(pheno = paste0("n", pheno),
           longname = paste0("n", longname),
           output = paste0("n", output),
           pheno_type = "OTU_NA"),
  annot %>%
    mutate(pheno = paste0("b", pheno),
           longname = paste0("b", longname),
           output = paste0("b", output),
           pheno_type = "OTU_Bin"))
```


```{r}
botu <- zotu <- notu <- readRDS(file.path(datapath, "otu",
                         "phe_otu_cr97_filter1010.rds"))
colnames(zotu) <- paste0("z", colnames(zotu))
colnames(notu) <- paste0("n", colnames(notu))
notu[notu == 0] <- NA
colnames(botu) <- paste0("b", colnames(botu))
botu[botu > 0] <- 1
```

## Now write stuff back out

**NOTE: What is missing is peaks for binary form data.**

```{r}
saveRDS(bind_rows(peaks_na, peaks_zero), file = file.path(datapath, "otu", "peaks_OTU_CR.rds"))
```

```{r}
saveRDS(cbind(notu, zotu, botu), file = file.path(datapath, "otu", "pheno_OTU_CR.rds"))
```

```{r}
analyses_otu <- analyses_tbl %>%
  filter(pheno_group == "otu") %>%
  filter(row_number(sex) == 1) %>%
  mutate(pheno_group = "OTU_Closed_Ref") %>%
  select(-pheno,-output,-longname,-pheno_type)
```

```{r}
analyses_otu <- inner_join(annot, analyses_otu, by = "pheno_group")
```

```{r}
analyses_otu %>% select(pheno,longname,pheno_type) %>% filter(grepl("?otu45363", pheno))
```

```{r}
saveRDS(analyses_otu, file = file.path(datapath, "otu", "analyses_OTU_CR.rds"))
```

